services:
  app:
    depends_on:
      - postgresql
    image: "quay.io/yborgess/todo-list-quarkus-boot-backend:latest"
    container_name: "todo-list-app"
    ports:
      - 8080:8080
    environment:
      - QUARKUS_PROFILE=prod
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/todos_db
      - QUARKUS_DATASOURCE_PASSWORD=password
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_HTTP_CORS_ORIGINS=*
